require "user.conf.nvim-autopairs"
require "user.conf.nvim-comment"
require "user.conf.nvim-notify"
require "user.conf.toggleterm"
require "user.conf.lualine"
require "user.conf.telescope"
require "user.conf.cmp"
